/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.freshsupasulley.lwjobs.test;

import io.github.freshsupasulley.lwjobs.OBSController;
import io.github.freshsupasulley.lwjobs.impl.GetSceneListRequest;
import org.junit.jupiter.api.Test;

class LibraryTest {
	
	@Test
	void someLibraryMethodReturnsTrue()
	{
		OBSController c = new OBSController();
		c.connect("ws://localhost:4444");
		
		var response = c.build(new GetSceneListRequest()).complete();
		System.out.println("CURRENT SCENE: " + response.getCurrentScene());
	}
}
